name: Deploy Portfolio Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            # Stop the current process if it's running
            echo "Stopping current process..."
            pm2 stop portfolio || true
            cd ${{ secrets.DEPLOY_PATH || '/home/ubuntu/portfolio' }}
            # Pull the latest code from the repository
            echo "Pulling latest code..."
            git pull origin main
            # Install dependencies and build the project
            echo "Installing dependencies and building the project..."
            npm ci 
            # Build the project
            echo "Building the project..."
            npm run build
            # Start the application using PM2
            echo "Starting the application..."
            pm2 reload portfolio || pm2 start npm --name "portfolio" -- start